### ISSUE TITLE
Server Profile Icons not square

### ISSUE THREAD

**Issue by FoxGames01** [craftablescience/Discord-Square-Theme#1]
Server profile icons are not showing square (default) and the status in the avatars are not displaying properly

**Comment by craftablescience** [comment]
Are you using another theme in tandem with this one? I reinstalled this theme and it works just as well as when I made it

**Comment by FoxGames01** [comment]
Disabling the mask in everything solves the problem, i dont know if it can bring some visual bug but it works
```
* {
    /* REMEMBER, NO CIRCLE */
    border-radius: 0px !important;
    mask: none !important;
}
```

**Comment by craftablescience** [comment]
Can I get the names of the theme(s) and/or plugin(s) modifying your server bar?

**Comment by craftablescience** [comment]
I don't want to introduce any visual bugs, I know masks are used in a lot of places. Closing this as a wontfix
